version: '3.8'

services:
  database:
    image: mariadb:10.5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "/srv/pterodactyl/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "secure_root_password"  # Root password for MariaDB
      MYSQL_DATABASE: "panel"  # Database name
      MYSQL_USER: "pterodactyl"  # Username for the panel database
      MYSQL_PASSWORD: "secure_db_password"  # Password for the panel database
  cache:
    image: redis:alpine
    restart: always
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - cache
    volumes:
      - "/srv/pterodactyl/var/:/app/var/"
      - "/srv/pterodactyl/nginx/:/etc/nginx/http.d/"
      - "/srv/pterodactyl/certs/:/etc/letsencrypt/"
      - "/srv/pterodactyl/logs/:/app/storage/logs"
    environment:
      APP_KEY: "base64:YourAppKeyHere=="  # Generate an app key later
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "cache"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "panel"
      DB_USERNAME: "pterodactyl"
      DB_PASSWORD: "secure_db_password"  # Same as in the database service
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "mail.example.com"
      MAIL_PORT: "587"
      MAIL_USERNAME: "your_email@example.com"
      MAIL_PASSWORD: "your_email_password"
      MAIL_ENCRYPTION: "tls"
      MAIL_FROM: "your_email@example.com"
networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16
        
